### ISSUE TITLE
Read/Write parameters causing NPE when write is requesting value that has already been read.

### ISSUE THREAD

**Issue by dpwspoon** [k3po/k3po#142]
This is probably a Threading race and is causing kaazing/gateway#41.

**Comment by dpwspoon** [comment]
Stack trace of NPE is below.  There are write notify barriers and then read await barriers before the access that is causing the problem.
ex

```
# in accept #1
read /(?<up>.*)/
read notify GO
# in accept stream #2
write await GO
write ${up}
```

So we could sync everything on the barriers

Stack trace
```
java.lang.NullPointerException
	at org.kaazing.k3po.lang.el.ByteArrayTypeConverter.coerceToByteArray(ByteArrayTypeConverter.java:74)
	at org.kaazing.k3po.lang.el.ByteArrayTypeConverter.convert(ByteArrayTypeConverter.java:37)
	at de.odysseus.el.tree.Bindings.convert(Bindings.java:138)
	at de.odysseus.el.tree.impl.ast.AstNode.getValue(AstNode.java:33)
	at de.odysseus.el.TreeValueExpression.getValue(TreeValueExpression.java:122)
	at org.kaazing.k3po.driver.behavior.handler.codec.WriteExpressionEncoder.encode(WriteExpressionEncoder.java:45)
	at org.kaazing.k3po.driver.behavior.handler.command.WriteHandler.invokeCommand(WriteHandler.java:52)
	at org.kaazing.k3po.driver.behavior.handler.command.AbstractCommandHandler$1.operationComplete(AbstractCommandHandler.java:48)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:413)
	at org.jboss.netty.channel.DefaultChannelFuture.setSuccess(DefaultChannelFuture.java:362)
	at org.kaazing.k3po.driver.netty.channel.CompositeChannelFuture$NotifyingListener.operationComplete(CompositeChannelFuture.java:204)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:418)
	at org.jboss.netty.channel.DefaultChannelFuture.setSuccess(DefaultChannelFuture.java:362)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:220)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromTaskLoop(AbstractNioWorker.java:151)
	at org.jboss.netty.channel.socket.nio.AbstractNioChannel$WriteTask.run(AbstractNioChannel.java:335)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:372)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:296)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[DEBUG] [id: 0xd2df8113] close
[DEBUG] channel disconnected
```

**Comment by dpwspoon** [comment]
I believe this bug is related to this stack trace 
```
javax.el.PropertyNotFoundException: Cannot resolve identifier 'randO'
	at de.odysseus.el.tree.impl.ast.AstIdentifier.eval(AstIdentifier.java:93)
	at de.odysseus.el.tree.impl.ast.AstEval.eval(AstEval.java:51)
	at de.odysseus.el.tree.impl.ast.AstNode.getValue(AstNode.java:31)
	at de.odysseus.el.TreeValueExpression.getValue(TreeValueExpression.java:122)
	at org.kaazing.k3po.driver.behavior.handler.codec.WriteExpressionEncoder.encode(WriteExpressionEncoder.java:50)
	at org.kaazing.k3po.driver.behavior.handler.command.WriteHandler.invokeCommand(WriteHandler.java:52)
	at org.kaazing.k3po.driver.behavior.handler.command.AbstractCommandHandler$1.operationComplete(AbstractCommandHandler.java:48)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:413)
	at org.jboss.netty.channel.DefaultChannelFuture.setSuccess(DefaultChannelFuture.java:362)
	at org.kaazing.k3po.driver.netty.channel.CompositeChannelFuture$NotifyingListener.operationComplete(CompositeChannelFuture.java:204)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:418)
	at org.jboss.netty.channel.DefaultChannelFuture.setSuccess(DefaultChannelFuture.java:362)
	at org.kaazing.k3po.driver.behavior.handler.event.ConnectedHandler.channelConnected(ConnectedHandler.java:36)
	at org.kaazing.k3po.driver.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:37)
	at org.kaazing.k3po.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream0(SimplePrepareUpstreamHandler.java:42)
	at org.kaazing.k3po.driver.behavior.handler.ExecutionHandler.handleUpstream1(ExecutionHandler.java:161)
	at org.kaazing.k3po.driver.behavior.handler.event.AbstractEventHandler.handleUpstream1(AbstractEventHandler.java:107)
	at org.kaazing.k3po.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:157)
	at org.kaazing.k3po.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:32)
	at org.kaazing.k3po.driver.behavior.handler.event.AbstractEventHandler.handleUpstream1(AbstractEventHandler.java:96)
	at org.kaazing.k3po.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:157)
	at org.kaazing.k3po.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:32)
	at org.kaazing.k3po.driver.behavior.handler.event.AbstractEventHandler.handleUpstream1(AbstractEventHandler.java:96)
	at org.kaazing.k3po.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:157)
	at org.kaazing.k3po.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:32)
	at org.jboss.netty.channel.Channels.fireChannelConnected(Channels.java:227)
	at org.jboss.netty.channel.socket.nio.NioWorker$RegisterTask.run(NioWorker.java:162)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:372)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:296)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)


```

Juel is not thread safe which can result in Null values and unresolved variables.

The cause is in AstIdentifier where calling getValue is setting global state on whether a property is resolved or not in the context.  That global knowledge can be manipulated by other threads calling get and set value.

```
		Object result = context.getELResolver().getValue(context, null, name);
		if (!context.isPropertyResolved()) {
			throw new PropertyNotFoundException(LocalMessages.get("error.identifier.property.notfound", name));
		}

```

An issue has been filed against [Juel](https://github.com/beckchr/juel/issues/87) on whether to resolve this in the library.  Until then I have syncronized(context) on all calls to Expression.getValue(context) and Expression.setValue(context)
