### ISSUE TITLE
Specification.ws: SocketException with Broken Pipe as connection is closed prematurely

### ISSUE THREAD

**Issue by sanjay-saxena** [k3po/k3po#191]
When `ClosingHandshakeIT.shouldCompleteCloseHandshakeWhenServerSendCloseFrameWithCode1000AndReasonUsingMessageReader()` test is executed using `server.send.close.frame.with.code.1000.and.reason/handshake.response.and.frames` script, the following exception is seen sporadically:

```
shouldCompleteCloseHandshakeWhenServerSendCloseFrameWithCode1000AndReasonUsingMessageReader(org.kaazing.netx.ws.specification.ClosingHandshakeIT)  Time elapsed: 0.029 sec  <<< ERROR!
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:138)
	at org.kaazing.netx.http.internal.HttpURLConnectionHandler$TcpOutputStream.write(HttpURLConnectionHandler.java:484)
	at org.kaazing.netx.ws.internal.io.OutgoingSentinelExtension.encodeMaskAndPayload(OutgoingSentinelExtension.java:300)
	at org.kaazing.netx.ws.internal.io.OutgoingSentinelExtension.validateAndEncodeCloseFrame(OutgoingSentinelExtension.java:269)
	at org.kaazing.netx.ws.internal.io.OutgoingSentinelExtension.access$100(OutgoingSentinelExtension.java:50)
	at org.kaazing.netx.ws.internal.io.OutgoingSentinelExtension$3.accept(OutgoingSentinelExtension.java:82)
	at org.kaazing.netx.ws.internal.ext.WebSocketContext.onCloseSent(WebSocketContext.java:125)
	at org.kaazing.netx.ws.internal.WebSocketOutputStateMachine.processFrame(WebSocketOutputStateMachine.java:85)
	at org.kaazing.netx.ws.internal.WsURLConnectionImpl.processOutgoingFrame(WsURLConnectionImpl.java:730)
	at org.kaazing.netx.ws.internal.io.WsOutputStream.writeClose(WsOutputStream.java:189)
	at org.kaazing.netx.ws.internal.WsURLConnectionImpl.sendClose(WsURLConnectionImpl.java:872)
	at org.kaazing.netx.ws.internal.WsURLConnectionImpl.sendCloseIfNecessary(WsURLConnectionImpl.java:758)
	at org.kaazing.netx.ws.internal.io.WsMessageReader$3.accept(WsMessageReader.java:187)
	at org.kaazing.netx.ws.internal.ext.WebSocketContext.onCloseReceived(WebSocketContext.java:65)
	at org.kaazing.netx.ws.internal.WebSocketInputStateMachine.processFrame(WebSocketInputStateMachine.java:92)
	at org.kaazing.netx.ws.internal.WsURLConnectionImpl.processIncomingFrame(WsURLConnectionImpl.java:726)
	at org.kaazing.netx.ws.internal.io.WsMessageReader.readDataFrameFully(WsMessageReader.java:634)
	at org.kaazing.netx.ws.internal.io.WsMessageReader.next(WsMessageReader.java:281)
	at org.kaazing.netx.ws.specification.ClosingHandshakeIT.shouldCompleteCloseHandshakeWhenServerSendCloseFrameWithCode1000AndReasonUsingMessageReader(ClosingHandshakeIT.java:244)
```

This is happening because the aforementioned script closes the connection without reading the status code and the reason for the CLOSE frame. To fix this issue, the following line should be added to the script after the mask is read:

```
read [0x03 0xe8] ${writeReason}
````

**Comment by cmebarrow** [comment]
@sanjay-saxena Is this a bug in k3po driver or just a bug in the spec script?

**Comment by a-zuckut** [comment]
I think this issue has been fixed?
