### ISSUE TITLE
FAILURE! - in org.kaazing.specification.http.rfc7230.MessageFormatIT

### ISSUE THREAD

**Issue by a-zuckut** [k3po/k3po#202]
```code
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.kaazing.specification.http.rfc7231.RequestHeaderFieldsIT
Tests run: 3, Failures: 0, Errors: 0, Skipped: 3, Time elapsed: 0.013 sec - in org.kaazing.specification.http.rfc7231.RequestHeaderFieldsIT
Running org.kaazing.specification.http.rfc7231.RequestMethodsIT
Tests run: 4, Failures: 0, Errors: 0, Skipped: 4, Time elapsed: 0.006 sec - in org.kaazing.specification.http.rfc7231.RequestMethodsIT
Running org.kaazing.specification.http.rfc7235.HeaderFieldDefinitionsIT
Tests run: 7, Failures: 0, Errors: 0, Skipped: 7, Time elapsed: 0.012 sec - in org.kaazing.specification.http.rfc7235.HeaderFieldDefinitionsIT
Running org.kaazing.specification.http.rfc7235.AuthIT
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.43 sec - in org.kaazing.specification.http.rfc7235.AuthIT
Running org.kaazing.specification.http.rfc7230.MessageRoutingIT
line 5:29 token recognition error at: '"\r\n\"\n'
line 6:31 token recognition error at: '"\r\n\"\n'
line 16:28 token recognition error at: '"\r\n\"\n'
line 17:30 token recognition error at: '"\r\n\"\n'
line 5:31 token recognition error at: '"\r\n\"\n'
line 15:30 token recognition error at: '"\r\n\"\n'
Tests run: 17, Failures: 0, Errors: 0, Skipped: 11, Time elapsed: 0.454 sec - in org.kaazing.specification.http.rfc7230.MessageRoutingIT
Running org.kaazing.specification.http.rfc7230.ConnectionManagementIT
Tests run: 12, Failures: 0, Errors: 0, Skipped: 3, Time elapsed: 0.709 sec - in org.kaazing.specification.http.rfc7230.ConnectionManagementIT
Running org.kaazing.specification.http.rfc7230.ArchitectureIT
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.588 sec - in org.kaazing.specification.http.rfc7230.ArchitectureIT
Running org.kaazing.specification.http.rfc7230.TransferCodingsIT
Tests run: 6, Failures: 0, Errors: 0, Skipped: 4, Time elapsed: 0.127 sec - in org.kaazing.specification.http.rfc7230.TransferCodingsIT
Running org.kaazing.specification.http.rfc7230.MessageFormatIT
Tests run: 25, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.786 sec <<< FAILURE! - in org.kaazing.specification.http.rfc7230.MessageFormatIT
inboundShouldAcceptHeaders(org.kaazing.specification.http.rfc7230.MessageFormatIT)  Time elapsed: 0.079 sec  <<< FAILURE!
org.junit.ComparisonFailure: Specified behavior did not match expected:<[connect http://localhost:8080/
connected
write method "GET"
write header "some" "header"
write close]
accept http://local...> but was:<[]
accept http://local...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.kaazing.k3po.junit.rules.SpecificationStatement.evaluate(SpecificationStatement.java:132)
	at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Results :
Failed tests: 
  MessageFormatIT.inboundShouldAcceptHeaders Specified behavior did not match expected:<[connect http://localhost:8080/
connected
write method "GET"
write header "some" "header"
write close]
accept http://local...> but was:<[]
accept http://local...>
Tests run: 88, Failures: 1, Errors: 0, Skipped: 32

**Comment by brennangaunce** [comment]
@a-zuckut Please put the link to the Travis build where this failed.
@dpwspoon David - can you take a look at this? (Assign to yourself...)

**Comment by a-zuckut** [comment]
The link in the Travis build in which it failed: 
https://travis-ci.org/k3po/k3po/jobs/68402219

**Comment by cmebarrow** [comment]
This is very similar to #229 failure, probably same issue.

**Comment by cmebarrow** [comment]
Saw same failure in MessageFormatIT.inboundShouldAcceptHeaders and ResponseStatusCodesIT.proxyShouldReturn504ResponseWhenServerDisconnects in Travis build 32 on my forked repository in a branch based on dev containing only some test script fixes. Console output from this build is available at:
[build32_diagnostics_http_fail_k3o_issue_202.txt](https://files.zenhub.io/564395c9e5b473fe074acd8c)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by cmebarrow** [comment]
John suggested the issue could be that in the k3po logic for finishing the execution of a test if a connect future has not been fulfilled (or its listeners fired?) then the entire connect stream is reported as not having executed, even if it actually did execute.
