### ISSUE TITLE
tcp script with client close closed server closed sometimes fails with disconnected instead of closed

### ISSUE THREAD

**Issue by cmebarrow** [k3po/k3po#222]
Test case (added to driver BehaviorIT) is 
```
    @TestSpecification("closed.vs.disconnected.issue")
    @Test
    public void closeVsDisconnectedIssue() throws Exception {
        //k3po.start();
        k3po.awaitBarrier("HANDSHAKE_COMPLETE");
        Thread.sleep(3000);
        k3po.notifyBarrier("TICK_ONE");
        k3po.finish();
    }
```
using the script:
[closed.vs.disconnected.issue.rpt | uploaded via ZenHub](https://files.zenhub.io/56143285ac1ef3cd3ae92c9b)

If this test is run repeatedly, sometimes it fails with 
```
org.junit.ComparisonFailure: Specified behavior did not match expected:<...e notify TICK_TWO
 
[clos]ed

# ============= ...> but was:<...e notify TICK_TWO
 
[disconnect]ed

# ============= ...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.kaazing.k3po.driver.internal.test.utils.K3poTestStatement.evaluate(K3poTestStatement.java:123)
```

**Comment by cmebarrow** [comment]
Test case is available in my branch [k3po_issue_222_close_vs_disconnected](https://github.com/cmebarrow/k3po/tree/k3po_issue_222_close_vs_disconnected)

**Comment by cmebarrow** [comment]
This bug is blocking script project for the idle timeout extension.

**Comment by cmebarrow** [comment]
Wireshark of the test failing shows there is a clean TCP FIN ACK sequence so the event on client conversation should have been closed not disconnected:

[closed.vs.disconnected.pcap | uploaded via ZenHub](https://files.zenhub.io/561435c7ac1ef3cd3ae92cc5)

**Comment by jfallows** [comment]
Recommend comparing the observed and actual scripts logged by k3po when this issue reproduces.

Since `closed` in the script should imply `disconnected`, `unbound`, `closed` with all implicit events injected, then the test failure described here seems to imply either that `disconnected` and `unbound` were not injected, hence `disconnected` observed at runtime when `closed` was expected, or that `disconnected` was somehow delivered a second time at runtime after `disconnected` and `unbound` were already observed. 

This can also be verified via the trace log of k3po while running this failure scenario.

**Comment by cmebarrow** [comment]
Debug k3po output is here:
[issue_222_k3po_debug_output.txt | uploaded via ZenHub](https://files.zenhub.io/56158df701d0668e74638394)

**Comment by cmebarrow** [comment]
It appears the problem can be worked around by not putting the NOTIFY between close and closed in the client portion of the script: moving the line "write notify TICK_TWO" before the preceding close seems to resolve the issue.

**Comment by irina-mitrea-luxoft** [comment]
I have attempted to use the above-described workaround for the idle timeout extension no data sent by server scenario. The vast majority of attempts to run the test case were successful, but I still encountered a couple of sporadic failures, the test failing in this instance with a timeout. 

I am attaching my .rpt scripts and k3po debug log for the test below in one of the sporadic timeout occurrences:

```
    @Specification({
        "no.data.sent.by.server.client.timeout/request",
        "no.data.sent.by.server.client.timeout/response" })
    @Test
    public void noDataSentByServerClientTimeout() throws Exception {
        k3po.start();
        k3po.awaitBarrier("HANDSHAKE_COMPLETE");
        Thread.sleep(3000);
        k3po.notifyBarrier("TICK_ONE");
        k3po.finish();
    }
```


[request.txt | uploaded via ZenHub](https://files.zenhub.io/5616473f01d0668e74638b08)

[response.txt | uploaded via ZenHub](https://files.zenhub.io/5616474201d0668e74638b09)

[issue_222_k3po_debug_output_timeout.txt | uploaded via ZenHub](https://files.zenhub.io/5616474501d0668e74638b0a)

**Comment by cmebarrow** [comment]
@irina-mitrea-luxoft I don't see a failure in your attached issue_222_k3po_debug...txt file. Did you attach the wrong file? It like case where it passed

**Comment by irina-mitrea-luxoft** [comment]
@cmebarrow This should be the correct log, the failure scenario had the channel disconnected prior to sending notify to TICK_ONE, as in the above log. I can attempt to reproduce the issue again, if needed.

**Comment by irina-mitrea-luxoft** [comment]
@cmebarrow I see that no FAILURE is specifically present in the log, I will attempt to reproduce the issue again and confront the logs.

**Comment by irina-mitrea-luxoft** [comment]
@cmebarrow Attaching a failure log. The failure trace is as follows:

**Comment by irina-mitrea-luxoft** [comment]
@cmebarrow Attaching a failure log. The failure trace is as follows:

```
org.junit.ComparisonFailure: Specified behavior did not match expected:<...ify TICK_TWO

close
[clos]ed
accept tcp://127....> but was:<...ify TICK_TWO

close
[disconnect]ed
accept tcp://127....>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.kaazing.k3po.junit.rules.SpecificationStatement.evaluate(SpecificationStatement.java:127)
	at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```
Please note that more that 100 test runs were needed in order to encounter one failure.
[201510122034_noDataSentByServerClientTimeout.txt | uploaded via ZenHub](https://files.zenhub.io/561bf003592eadf906d5fcaa)

**Comment by cmebarrow** [comment]
I have a fix ready for this bug: PR #243

**Comment by cmebarrow** [comment]
Closing because pull request #243 is now merged

**Comment by cmebarrow** [comment]
Reopening because this was closed by accident. Pull request #243 fixes issue #223.

**Comment by cmebarrow** [comment]
The problem reproduces that the following simplified test case, with just k3po.finish() in the JUnit test method:
```
# ============= request ==================
connect tcp://127.0.0.1:8001
connected

# Connection request
write "GET /echo?.kl=Y HTTP/1.1\r\n"
write "Upgrade: websocket\r\n"
write "Connection: Upgrade\r\n"
write "Host: localhost:8001\r\n"
write "Origin: http://localhost:8001\r\n"
write "Sec-WebSocket-Key: ePYyZxvR5fDLh/oEugMjbA==\r\n"
write "Sec-WebSocket-Version: 13\r\n"
write "Sec-WebSocket-Extensions: x-kaazing-idle-timeout\r\n"
write "\r\n"

# 101 Response

read "HTTP/1.1 101 Web Socket Protocol Handshake\r\n"
read "Connection: Upgrade\r\n"
read "Date:" /.*/ "\r\n"
read "Sec-WebSocket-Accept" /.*/ "\r\n"
read "Sec-WebSocket-Extensions: x-kaazing-idle-timeout; timeout=2000\r\n"
read "Server: Kaazing Gateway\r\n"
read "Upgrade: websocket\r\n"
read "\r\n"

read notify HANDSHAKE_COMPLETE

write await HANDSHAKE_COMPLETE

close

write notify CLIENT_CLOSE_ISSUED

# If the following line is uncommented the test passes
# read await CLIENT_CLOSE_ISSUED
 
closed

# ============= response ==================
accept tcp://127.0.0.1:8001
accepted
connected

# Connection request
read "GET /echo?.kl=Y HTTP/1.1\r\n"
read "Upgrade: websocket\r\n"
read "Connection: Upgrade\r\n"
read "Host: localhost:8001\r\n"
read "Origin: http://localhost:8001\r\n"
read "Sec-WebSocket-Key: ePYyZxvR5fDLh/oEugMjbA==\r\n"
read "Sec-WebSocket-Version: 13\r\n"
read "Sec-WebSocket-Extensions: x-kaazing-idle-timeout\r\n"
read "\r\n"

# 101 Response

write "HTTP/1.1 101 Web Socket Protocol Handshake\r\n"
write "Connection: Upgrade\r\n"
write "Date: Fri, 31 Dec 1999 23:59:59 GMT\r\n"
write "Sec-WebSocket-Accept" "TXCKJSpylVJ7v9ZGLGbt58vypzE=\r\n"
write "Sec-WebSocket-Extensions: x-kaazing-idle-timeout; timeout=2000\r\n"
write "Server: Kaazing Gateway\r\n"
write "Upgrade: websocket\r\n"
write "\r\n"

read await CLIENT_CLOSE_ISSUED

closed

```

**Comment by cmebarrow** [comment]
Debugging shows the issue is that close event processing causes disconnected to be fired before all the events before the close (especially read) have had a change to fire all the listeners on their composite futures. So when close is fired on the composite listener for the "write notify CLIENT_CLOSE_ISSUED" event the read future has not yet been counted by that future as having succeeded. Close therefore does not fulfil the future for "write notify CLIENT_CLOSE_ISSUED".
