### ISSUE TITLE
Can't build k3po on Windows: driver module gives test failures, script not found

### ISSUE THREAD

**Issue by cmebarrow** [k3po/k3po#230]
7 tests fail, all with failures similar to the following:
```
connectFinishedWithBarriers(org.kaazing.k3po.driver.internal.K3poIT)  Time elapsed: 0.006 sec  <<< ERROR!
java.lang.RuntimeException: Script not found: org\kaazing\specification\control\connect.finished.with.barriers.rpt
        at org.kaazing.k3po.driver.internal.control.handler.ControlServerHandler.aggregateScript(ControlServerHandler.java:178)
        at org.kaazing.k3po.driver.internal.test.utils.ScriptTestRunner.call(ScriptTestRunner.java:57)
        at org.kaazing.k3po.driver.internal.test.utils.ScriptTestRunner.call(ScriptTestRunner.java:27)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:745)
```
This is a regression due to commit fd70a86. If I go back to the commit before that (4ca5d1c) it builds fine.

**Comment by cmebarrow** [comment]
This regression is caused by the call to "normalize()" followed by the reassignment of scriptNameWithExtension in ControlServerHandler:
```
            Path scriptPath = Paths.get(scriptNameWithExtension).normalize();
            scriptNameWithExtension = scriptPath.toString();
```
When the input parameter (scriptNameWithExtension) is `org/kaazing/specification/control/accept.finished.rpt`. this code causes it to get reset to `org\kaazing\specification\control\accept.finished.rpt`. The result is scriptLoader.getResource(scriptNameWithExtension) returns null instead of finding the resource.

**Comment by jitsni** [comment]
Fixed by this commit:
https://github.com/k3po/k3po/commit/1862508cdc58686f5a2a7c1f4dea7193707bf7b2
