### ISSUE TITLE
Tests using K3poRule sometimes fail randomly with InterruptedException during Latch.awaitPrepared()

### ISSUE THREAD

**Issue by cmebarrow** [k3po/k3po#236]
Here is one example:
```
BaseFramingIT.shouldEchoTextFrameWithPayloadLength125 FAILED with exception java.lang.InterruptedException
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1302)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at org.kaazing.k3po.junit.rules.Latch.awaitPrepared(Latch.java:58)
	at org.kaazing.k3po.junit.rules.SpecificationStatement.evaluate(SpecificationStatement.java:63)
	at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)

```

**Comment by cmebarrow** [comment]
The only places in the k3po code I can find that call Thread.interrupt are in Latch.notifyException and Latch.setInterruptOnException.
