### ISSUE TITLE
specifications/http build failed with test timeout in ResponseStatusCodesIT

### ISSUE THREAD

**Issue by cmebarrow** [k3po/k3po#252]
ResponseStatusCodesIT.proxyShouldReturn504ResponseWhenServerDisconnects:61 TestTimedOut

Build output (relevant parts) with k3po debug info are at the link below (this was a Travis build). This was a special bill done with maven -X flag and the root pom.xml edited to remove all specification modules except bbosh, http and k3po.control to avoid exploding the Travis limit on build output size.

[out.bbosh_http_and_deps_only.http.timeout.fail.txt](https://github.com/k3po/k3po/files/25760/out.bbosh_http_and_deps_only.http.timeout.fail.txt)

**Comment by cmebarrow** [comment]
The attached output file shows the timeout occurs in 
```
	at org.kaazing.k3po.junit.rules.Latch.awaitFinished(Latch.java:126)
	at org.kaazing.k3po.junit.rules.K3poRule.finish(K3poRule.java:166)
	at org.kaazing.specification.http.rfc7231.ResponseStatusCodesIT.proxyShouldReturn504ResponseWhenServerDisconnects(ResponseStatusCodesIT.java:61)

```
Curiously the observed script reported in the k3po debug messages is exactly as expected. So it seems the test passed just time but somehow the k3po latch did not get unlocked.
