### ISSUE TITLE
Using 'connect await BARRIER' instead of `write await BARRIER` causes ScriptParseException

### ISSUE THREAD

**Issue by sanjay-saxena** [k3po/k3po#257]
Originally, the script used `write await BARRIER` like this:

```
connect http://localhost:8000/index.html
connected

write method "GET"
....

read status "200" /.*/
read header "ETag" /(?<entityTag>.+)/
read notify BARRIER

connect http://localhost:8000/index.html
connected

write await BARRIER
write method "DELETE"
...
write header "If-Match" ${entityTag}, "\"tag1\"", "\"tag2\""
...
write flush

read status "200" /.*/
```

Modifying the script to use `connect await BARRIER`(instead of  `write await BARRIER`) after the `connect` as shown below:

```
connect http://localhost:8000/index.html
connected

write method "GET"
....

read status "200" /.*/
read header "ETag" /(?<entityTag>.+)/
read notify BARRIER

connect http://localhost:8000/index.html
connect await BARRIER
connected

write method "DELETE"
...
write header "If-Match" ${entityTag}, "\"tag1\"", "\"tag2\""
...
write flush

read status "200" /.*/
```

results in a ScriptParseException as shown below:

```
line 15:0 no viable alternative at input 'connect'
[ERROR] Caught exception trying to parse script. Sending error to client
org.kaazing.k3po.lang.internal.parser.ScriptParseException: org.kaazing.k3po.lang.internal.parser.ScriptParseException: line 15:0: unexpected character: 'c'
	at org.kaazing.k3po.lang.internal.parser.ScriptParserImpl.parse(ScriptParserImpl.java:74)
	at org.kaazing.k3po.driver.internal.behavior.parser.Parser.parse(Parser.java:42)
	at org.kaazing.k3po.driver.internal.Robot.prepare(Robot.java:148)
	at org.kaazing.k3po.driver.internal.control.handler.ControlServerHandler.prepareReceived(ControlServerHandler.java:119)
	at org.kaazing.k3po.driver.internal.control.handler.ControlUpstreamHandler.messageReceived(ControlUpstreamHandler.java:37)
	at org.jboss.netty.handler.logging.LoggingHandler.handleUpstream(LoggingHandler.java:332)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.kaazing.k3po.lang.internal.parser.ScriptParseException: line 15:0: unexpected character: 'c'
	at org.kaazing.k3po.lang.internal.parser.ScriptParserImpl.createScriptParseException(ScriptParserImpl.java:171)
	at org.kaazing.k3po.lang.internal.parser.ScriptParserImpl.createScriptParseException(ScriptParserImpl.java:136)
	at org.kaazing.k3po.lang.internal.parser.ScriptParserImpl.parseWithStrategy(ScriptParserImpl.java:115)
	at org.kaazing.k3po.lang.internal.parser.ScriptParserImpl.parse(ScriptParserImpl.java:72)
```

**Comment by sanjay-saxena** [comment]
@jfallows clarified that the `connect await BARRIER` should be **before** the `connect`. With that change, I am no longer seeing `ScriptParseException`.
