### ISSUE TITLE
Using properties in scripts only works before accept or connect

### ISSUE THREAD

**Issue by cmebarrow** [k3po/k3po#353]
Wiki page [](https://github.com/k3po/k3po/wiki/Scripting-Language) says "Properties are the equivalent to variable definitions. They typically occur at the top of the script.". In fact, in the current implementation they **have** to occur at the top of the script. Otherwise the result is a prase exception with no clear indication of where the error is.

To reproduce:
- check out branch issue_#### from my fork
- Open the k3po.examples module in Eclipse
- Run a new test I added: MultipleFilesIT. This runs four scripts which together form the following script:
```
property location "tcp://localhost:8080"

connect ${location}
connected

property requestData "hello world"

write ${requestData}
read "hello client"

property location "tcp://localhost:8080"

accept ${location}
accepted
connected

read "hello world"
write "hello client"
```
-  Result is the test is reported as having failed with an InterruptedException, nd the k3po console output contains the following exception:
```
[ERROR] Caught exception trying to parse script. Sending error to client
org.kaazing.k3po.lang.internal.parser.ScriptParseException: org.kaazing.k3po.lang.internal.parser.ScriptParseException: error: unexpected keyword 'write'
	at org.kaazing.k3po.lang.internal.parser.ScriptParserImpl.parse(ScriptParserImpl.java:73)
	at org.kaazing.k3po.driver.internal.behavior.parser.Parser.parse(Parser.java:41)
	at org.kaazing.k3po.driver.internal.Robot.prepare(Robot.java:129)
	at org.kaazing.k3po.driver.internal.control.handler.ControlServerHandler.prepareReceived(ControlServerHandler.java:151)
	at org.kaazing.k3po.driver.internal.control.handler.ControlUpstreamHandler.messageReceived(ControlUpstreamHandler.java:36)
```
Full debug k3po console output is:
[k3po_debug_console_output.txt](https://github.com/k3po/k3po/files/419311/k3po_debug_console_output.txt)

The exceptions are extremely unhelpful, there is no indication of what the actual problem is.

**Comment by cmebarrow** [comment]
This bug makes it essentially impossible in practice to build product test cases by combining specification scripts to make more complex test cases.
