### ISSUE TITLE
k3po.awaitBarrier sometimes hangs, even though the barrier was in fact fired

### ISSUE THREAD

**Issue by cmebarrow** [k3po/k3po#379]
This bug is causing occasional failures in Kaazing Gateway test [JmxSessionPrincipalIT](https://github.com/kaazing/gateway/blob/develop/management/src/test/java/org/kaazing/gateway/management/jmx/JmxSessionPrincipalIT.java), randomly in any of the test methods ( especially when the second is unignored, or when a third is added using the same scripts and await calls. It Is always the third await that fails, in the code extract that is at the start of each test method:

```
    @Specification({
        "wsn.session.with.user.principal.joe",
        "wse.session.with.user.principal.joe",
        "wsn.session.with.user.principal.ann" })
    @Test
    public void sessionAttributePrincipalsShouldListUserPrincipals() throws Exception {
        k3po.start();

        k3po.awaitBarrier("JOE_WSN_SESSION_ESTABLISHED");
        k3po.awaitBarrier("JOE_WSE_SESSION_ESTABLISHED");
        k3po.awaitBarrier("ANN_WSN_SESSION_ESTABLISHED");
```
Here is the test output and wireshark for one failure case:
[JmxSessionPrincipalIT_random_fail.out.txt](https://github.com/k3po/k3po/files/577142/JmxSessionPrincipalIT_random_fail.out.txt)
[JmxSessionPrincipalIT_random_fail.pcap.zip](https://github.com/k3po/k3po/files/577143/JmxSessionPrincipalIT_random_fail.pcap.zip)

In this particular run, the first test method failed and the second succeeded. Looking at the wireshark, the two conversations with tcp.port == 11642 correspond to the k3po BBOSH cconversations for each test run. Both appear to indicate that the three barriers were in fact notified in each case.

**Comment by cmebarrow** [comment]
Looking at the wireshark, the two conversations with tcp.port == 11642 correspond to the k3po BBOSH conversations for each test run. Both appear to indicate that the three barriers were in fact notified in each case.  But in the first (failing) case, when the conversation lasted 20 seconds, the `FINISHED` event gets sent before `NOTIFIED barrier:ANN_WSN_SESSION_ESTABLISHED`. That probably explains the following error in the console output (JmxSessionPrincipalIT_random_fail.out.txt):
```
java.lang.IllegalArgumentException: Unrecognized event kind: NOTIFIED
	at org.kaazing.k3po.junit.rules.ScriptRunner.dispose(ScriptRunner.java:331)
	at org.kaazing.k3po.junit.rules.SpecificationStatement.evaluate(SpecificationStatement.java:126)
	at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	at org.kaazing.gateway.management.test.util.JmxRule$JmxStatement.evaluate(JmxRule.java:84)
```

**Comment by cmebarrow** [comment]
So the bug it appears to me that sometimes k3po server is sending a NOTIFIED event after FINISHED.

**Comment by dpwspoon** [comment]
This is a race between the notified and the finish arriving in an unexpected order to the junit program.  The scripts shouldn't really need a notify barrier here for Chris' use case but this is still a bug. 

I believe the proper fix is to make k3po junit more resilient as an await from junit could come at any time prior to the dispose command
