### ISSUE TITLE
Assume.assumeTrue doesn't work in robot tests

### ISSUE THREAD

**Issue by dpwspoon** [k3po/k3po#41]
```
    @Robotic(script = "echoTextFrameInIPv6Service")
    @Test
    public void proxyPreservesTextFrame() throws Exception {
            Assume.assumeTrue(false);
```

doesn't make the test pass. I think RobotRule should catch the exception thrown by assumeTrue. It is

```
org.junit.AssumptionViolatedException: got: <false>, expected: is <true>
	at org.junit.Assume.assumeThat(Assume.java:95)
	at org.junit.Assume.assumeTrue(Assume.java:41)
	at com.kaazing.gateway.transport.wsn.WsnIPv6IT.proxyPreservesTextFrame(WsnIPv6IT.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.kaazing.gateway.server.test.GatewayRule$GatewayStatement.evaluate(GatewayRule.java:69)
	at com.kaazing.robot.junit.rules.RoboticStatement.evaluate(RoboticStatement.java:65)
	at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
```

**Comment by jfallows** [comment]
Confirmed Assume supported by K3PO JUnit integration via k3po/k3po.java#9.
