### ISSUE TITLE
Better exception on parse failures reported via robot control

### ISSUE THREAD

**Issue by dpwspoon** [k3po/k3po#43]
This is a regression but I guess we never had a test for it.  The robot control is returning script parse exceptions, but with out any diagnostic data (like what line number).  This makes it more difficult to debug.

Tests need to be added for this as well

**Comment by dpwspoon** [comment]
Not seeing this anymore via @jfallows fix

```
org.kaazing.k3po.junit.rules.SpecificationException: Parse Error:org.kaazing.k3po.lang.parser.ScriptParseException: error: unexpected keyword 'asdfassadf'
	at org.kaazing.k3po.junit.rules.ScriptRunner.call(ScriptRunner.java:117)
	at org.kaazing.k3po.junit.rules.ScriptRunner.call(ScriptRunner.java:40)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:744)

```
