### ISSUE TITLE
NPE in K3po AgronaWorker

### ISSUE THREAD

**Issue by dpwspoon** [k3po/k3po#438]
```
	at org.kaazing.k3po.driver.internal.netty.bootstrap.agrona.AgronaWorker.readMessges(AgronaWorker.java:132)
	at org.kaazing.k3po.driver.internal.netty.bootstrap.agrona.AgronaWorker.run(AgronaWorker.java:96)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dpwspoon** [comment]
I'm not sure how this code occur from a threading policy, but I believe perhaps we should set the Remote address before firing events up the pipeline: 

Here: https://github.com/k3po/k3po/blob/7d130bf2eba14151f728c89c3ac667db59d3e55f/driver/src/main/java/org/kaazing/k3po/driver/internal/netty/bootstrap/channel/AbstractServerChannelChildHandler.java
```
    @Override
    @SuppressWarnings("unchecked")
    public void messageReceived(ChannelHandlerContext ctx, MessageEvent e) throws Exception {

        S serverChannel = (S) ctx.getAttachment();

        T childChannel = createChildChannel(serverChannel, e.getChannel());
        fireChannelOpen(childChannel);

        ChannelAddress localAddress = serverChannel.getLocalAddress();
        childChannel.setLocalAddress(localAddress);
        childChannel.setBound();
        fireChannelBound(childChannel, localAddress);

        ctx.setAttachment(childChannel);

        ctx.sendUpstream(e);

        // TODO: fire CONNECTED_BARRIER event to next pipeline
        // then fire CONNECTED event when future completes successfully
        ChannelAddress remoteAddress = localAddress.newEphemeralAddress();
        childChannel.setRemoteAddress(remoteAddress);
        childChannel.setConnected();
        fireChannelConnected(childChannel, remoteAddress);
    }
```

and here:

```
        @Override
        public void run() {
            serverChannel.setLocalAddress(localAddress);
            serverChannel.setBound();

            fireChannelBound(serverChannel, serverChannel.getLocalAddress());

            try {
                ChannelPipelineFactory pipelineFactory = serverChannel.getConfig().getPipelineFactory();
                ChannelPipeline pipeline = pipelineFactory.getPipeline();
                bindFuture.setSuccess();

                // fire child channel opened
                ChannelFactory channelFactory = serverChannel.getFactory();
                AgronaChildChannelSink channelSink = new AgronaChildChannelSink();
                AgronaChildChannel childChannel =
                        new AgronaChildChannel(serverChannel, channelFactory, pipeline, channelSink, serverChannel.worker);

                childChannel.setLocalAddress(serverChannel.getLocalAddress());
                fireChannelBound(childChannel, childChannel.getLocalAddress());

                childChannel.setRemoteAddress(childChannel.getLocalAddress());
                Channels.fireChannelConnected(childChannel, childChannel.getRemoteAddress());

                childChannel.worker.register(childChannel);
            }
            catch (Exception e) {
                bindFuture.setFailure(e);
            }
        }
```
